env:
  browser: true
  es2021: true
  node: true
  es6: true
extends: plugin:vue/vue3-essential
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - '@typescript-eslint'
  - vue
rules: {}
